# Treinamento

### Carregando Arquivo de Treinamento (.csv)

In [115]:
import pandas as pd
# Carregando dados do arquivo CSV
url = 'https://raw.githubusercontent.com/Kendy619/Perceptron-for-diabetes-disease/main/diabetes.csv'
base_Treinamento = pd.read_csv(url,sep=',', encoding = 'latin1').values
print("---------------------------------")
print("Dados dos Pacientes - TREINAMENTO")
print("---------------------------------")
print(base_Treinamento)
print("---------------------------------")

# Extração dos Atributos a serem utilizadas pela rede
print("Atributos de Entrada")
print("---------------------------------")
print(base_Treinamento[:, 0:8])

print("----------------------------")
print("Classificação Supervisionada")
print("----------------------------")
print(base_Treinamento[:, 8])

---------------------------------
Dados dos Pacientes - TREINAMENTO
---------------------------------
[[  6.    148.     72.    ...   0.627  50.      1.   ]
 [  1.     85.     66.    ...   0.351  31.      0.   ]
 [  8.    183.     64.    ...   0.672  32.      1.   ]
 ...
 [  5.    121.     72.    ...   0.245  30.      0.   ]
 [  1.    126.     60.    ...   0.349  47.      1.   ]
 [  1.     93.     70.    ...   0.315  23.      0.   ]]
---------------------------------
Atributos de Entrada
---------------------------------
[[  6.    148.     72.    ...  33.6     0.627  50.   ]
 [  1.     85.     66.    ...  26.6     0.351  31.   ]
 [  8.    183.     64.    ...  23.3     0.672  32.   ]
 ...
 [  5.    121.     72.    ...  26.2     0.245  30.   ]
 [  1.    126.     60.    ...  30.1     0.349  47.   ]
 [  1.     93.     70.    ...  30.4     0.315  23.   ]]
----------------------------
Classificação Supervisionada
----------------------------
[1. 0. 1. 0. 1. 0. 1. 0. 1. 1. 0. 1. 0. 1. 1. 1. 1

### Pré-processamento de Dados

In [116]:
import numpy as np 
from sklearn import preprocessing

# Binarizador de rótulo
lb = preprocessing.LabelBinarizer()
escaler = preprocessing.MinMaxScaler()

# Pregnancies
  
pregnancies = escaler.fit_transform(np.array(base_Treinamento[:, 0]).reshape(-1,1))


# Glucose

glucose = escaler.fit_transform(np.array(base_Treinamento[:, 1]).reshape(-1,1))

# BloodPressure

bloodpressure = escaler.fit_transform(np.array(base_Treinamento[:, 2]).reshape(-1,1))

# SkinThickness

skinthickness = escaler.fit_transform(np.array(base_Treinamento[:, 3]).reshape(-1,1))

# Insulin

insulin = escaler.fit_transform(np.array(base_Treinamento[:, 4]).reshape(-1,1))


# BMI
#bmi = lb.transform(base_Treinamento[:,5])   #NUMEROS DO TIPO FLOAT NÃO SÃO SUPORTADOS
bmi = escaler.fit_transform(np.array(base_Treinamento[:, 5]).reshape(-1,1))

# DiabetesPedigreeFunction
#diabetespedigreefunction = lb.transform(base_Treinamento[:,6])   #NUMEROS DO TIPO FLOAT NÃO SÃO SUPORTADOS
diabetespedigreefunction = escaler.fit_transform(np.array(base_Treinamento[:, 6]).reshape(-1,1))

# Age

age = escaler.fit_transform(np.array(base_Treinamento[:, 7]).reshape(-1,1))

# Separete classes
classes = base_Treinamento[:,8]

#Concatenação de Atributos (Colunas) 
atributos_norm = np.column_stack((pregnancies, glucose, bloodpressure, skinthickness, insulin, bmi, diabetespedigreefunction, age))

print("--------------------------------")
print("Atributos de Entrada - Numéricos")
print("--------------------------------")
print(atributos_norm)

print("----------------------------------------")
print("Classificação Supervisionada - Numéricos")
print("----------------------------------------")
diagnostico_norm = np.hstack((classes))
print(diagnostico_norm)

--------------------------------
Atributos de Entrada - Numéricos
--------------------------------
[[0.35294118 0.74371859 0.59016393 ... 0.50074516 0.23441503 0.48333333]
 [0.05882353 0.42713568 0.54098361 ... 0.39642325 0.11656704 0.16666667]
 [0.47058824 0.91959799 0.52459016 ... 0.34724292 0.25362938 0.18333333]
 ...
 [0.29411765 0.6080402  0.59016393 ... 0.390462   0.07130658 0.15      ]
 [0.05882353 0.63316583 0.49180328 ... 0.4485842  0.11571307 0.43333333]
 [0.05882353 0.46733668 0.57377049 ... 0.45305514 0.10119556 0.03333333]]
----------------------------------------
Classificação Supervisionada - Numéricos
----------------------------------------
[1. 0. 1. 0. 1. 0. 1. 0. 1. 1. 0. 1. 0. 1. 1. 1. 1. 1. 0. 1. 0. 0. 1. 1.
 1. 1. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 1. 1. 0. 0. 0. 1. 0. 1. 0. 0.
 1. 0. 0. 0. 0. 1. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 1. 0. 1. 0. 0. 0. 1. 0.
 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0.
 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1.

### Treinamento do Neurônio Perceptron

In [117]:
from sklearn.linear_model import Perceptron

# Treinamento do Perceptron a partir dos atributos de entrada e classificações
modelo = Perceptron()
modelo.fit(atributos_norm, diagnostico_norm)

print('Acurácia: %.3f' % modelo.score(atributos_norm, diagnostico_norm))

Acurácia: 0.629


### ----------------------------------------------------------------------------

# Validação do Aprendizado 

### Predição Simples

In [118]:
Luiz = [[6,148,72,35,0,33.6,0.627,50]]
print("Luiz", modelo.predict(Luiz))
Dosea= [[1,85,66,29,0,26.6,0.351,31]]
print("Dosea", modelo.predict(Dosea))

Luiz [1.]
Dosea [1.]


### Predição a partir de base de dados (.csv)

In [119]:
import pandas as pd
# Carregando dados do arquivo CSV
url = 'https://raw.githubusercontent.com/Kendy619/Perceptron-for-diabetes-disease/main/teste.csv'
base_Testes = pd.read_csv(url,sep=',', encoding = 'latin1').values
print("----------------------------")
print("Dados dos Pacientes - TESTES")
print("----------------------------")
print(base_Testes)
print("---------------------------------")

# Extração dos Atributos a serem utilizadas pela rede
print("Atributos de Entrada")
print("---------------------------------")
print(base_Testes[:, 0:8])

----------------------------
Dados dos Pacientes - TESTES
----------------------------
[[1.000e+00 8.100e+01 7.400e+01 4.100e+01 5.700e+01 4.630e+01 1.096e+00
  3.200e+01 0.000e+00]
 [3.000e+00 1.870e+02 7.000e+01 2.200e+01 2.000e+02 3.640e+01 4.080e-01
  3.600e+01 1.000e+00]
 [6.000e+00 1.620e+02 6.200e+01 0.000e+00 0.000e+00 2.430e+01 1.780e-01
  5.000e+01 1.000e+00]
 [4.000e+00 1.360e+02 7.000e+01 0.000e+00 0.000e+00 3.120e+01 1.182e+00
  2.200e+01 1.000e+00]
 [1.000e+00 1.210e+02 7.800e+01 3.900e+01 7.400e+01 3.900e+01 2.610e-01
  2.800e+01 0.000e+00]
 [3.000e+00 1.080e+02 6.200e+01 2.400e+01 0.000e+00 2.600e+01 2.230e-01
  2.500e+01 0.000e+00]
 [0.000e+00 1.810e+02 8.800e+01 4.400e+01 5.100e+02 4.330e+01 2.220e-01
  2.600e+01 1.000e+00]
 [8.000e+00 1.540e+02 7.800e+01 3.200e+01 0.000e+00 3.240e+01 4.430e-01
  4.500e+01 1.000e+00]
 [1.000e+00 1.280e+02 8.800e+01 3.900e+01 1.100e+02 3.650e+01 1.057e+00
  3.700e+01 1.000e+00]
 [7.000e+00 1.370e+02 9.000e+01 4.100e+01 0.000e+00 3.200e

### Pré-processamento de Dados

In [120]:
import numpy as np 
from sklearn import preprocessing

# Binarizador de rótulo
#lb = preprocessing.LabelBinarizer()

# Binarizador de rótulo
#lb = preprocessing.LabelBinarizer()
escaler = preprocessing.MinMaxScaler()

# Pregnancies
#pregnancies = lb.transform(base_Treinamento[:,0])  
pregnancies = escaler.fit_transform(np.array(base_Testes[:, 0]).reshape(-1,1))


# Glucose
#glucose = lb.transform(base_Treinamento[:,1])
glucose = escaler.fit_transform(np.array(base_Testes[:, 1]).reshape(-1,1))

# BloodPressure
#bloodpressure = lb.transform(base_Treinamento[:,2])
bloodpressure = escaler.fit_transform(np.array(base_Testes[:, 2]).reshape(-1,1))

# SkinThickness
#skinthickness = lb.transform(base_Treinamento[:,3])
skinthickness = escaler.fit_transform(np.array(base_Testes[:, 3]).reshape(-1,1))

# Insulin
#insulin = lb.transform(base_Treinamento[:,4])
insulin = escaler.fit_transform(np.array(base_Testes[:, 4]).reshape(-1,1))


# BMI

bmi = escaler.fit_transform(np.array(base_Testes[:, 5]).reshape(-1,1))

# DiabetesPedigreeFunction

diabetespedigreefunction = escaler.fit_transform(np.array(base_Testes[:, 6]).reshape(-1,1))

# Age
#age = lb.transform(base_Treinamento[:,7])
age = escaler.fit_transform(np.array(base_Testes[:, 7]).reshape(-1,1))

#Atributos categóricos com valores pequenas e grandes

#Concatenação de Atributos (Colunas) 
atributos_norm = np.column_stack((pregnancies, glucose, bloodpressure, skinthickness, insulin, bmi, diabetespedigreefunction, age))
print("--------------------------------")
print("Atributos de Entrada - Numéricos")
print("--------------------------------")
print(atributos_norm)


--------------------------------
Atributos de Entrada - Numéricos
--------------------------------
[[0.1        0.         0.47058824 0.85416667 0.11176471 1.
  0.91730769 0.22727273]
 [0.3        0.97247706 0.35294118 0.45833333 0.39215686 0.58403361
  0.25576923 0.31818182]
 [0.6        0.74311927 0.11764706 0.         0.         0.07563025
  0.03461538 0.63636364]
 [0.4        0.50458716 0.35294118 0.         0.         0.36554622
  1.         0.        ]
 [0.1        0.36697248 0.58823529 0.8125     0.14509804 0.69327731
  0.11442308 0.13636364]
 [0.3        0.24770642 0.11764706 0.5        0.         0.14705882
  0.07788462 0.06818182]
 [0.         0.91743119 0.88235294 0.91666667 1.         0.87394958
  0.07692308 0.09090909]
 [0.8        0.66972477 0.58823529 0.66666667 0.         0.41596639
  0.28942308 0.52272727]
 [0.1        0.43119266 0.88235294 0.8125     0.21568627 0.58823529
  0.87980769 0.34090909]
 [0.7        0.51376147 0.94117647 0.85416667 0.         0.39915966
  0.

### Predição da Base

In [121]:
base_Predicao = modelo.predict((atributos_norm))
print("Classificações: ", base_Predicao)

Classificações:  [1. 1. 1. 1. 0. 0. 1. 1. 1. 1. 1. 0. 1. 0. 1. 0. 0. 0. 0. 0. 0.]
